//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesira.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.UsersProfiles = new HashSet<UsersProfile>();
        }
    
        public long Id_Address { get; set; }
        public int Id_Country { get; set; }
        public string PhysicalAddress { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<UsersProfile> UsersProfiles { get; set; }
    }
}
