//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesira.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.Files = new HashSet<File>();
        }
    
        public long Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Trace { get; set; }
        public Nullable<long> Id_Prescription { get; set; }
        public long Id_Patient { get; set; }
        public long Id_Doctor { get; set; }
        public System.DateTime EndDate { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual User AppointmentDoctor { get; set; }
        public virtual User AppointmentPatient { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
