//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesira.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.DrugsDiseases = new HashSet<DrugsDiseas>();
            this.PrescriptionsDrugs = new HashSet<PrescriptionsDrug>();
        }
    
        public long Id { get; set; }
        public string GeneralName { get; set; }
        public string ComercialName { get; set; }
        public string Vendor { get; set; }
        public string OriginCountry { get; set; }
        public string PresentationForm { get; set; }
        public string ReductionClass { get; set; }
    
        public virtual ICollection<DrugsDiseas> DrugsDiseases { get; set; }
        public virtual ICollection<PrescriptionsDrug> PrescriptionsDrugs { get; set; }
    }
}
