//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesira.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionsDrug
    {
        public long Id_Prescription { get; set; }
        public long Id_Drug { get; set; }
        public int Quantity { get; set; }
        public int Days { get; set; }
        public int Id_Disease { get; set; }
        public long Id { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Drug Drug { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
