//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesira.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UsersProfiles = new HashSet<UsersProfile>();
            this.AppointmentsListForDoctor = new HashSet<Appointment>();
            this.AppointmentsListForPatient = new HashSet<Appointment>();
            this.PrescriptionsListForDoctor = new HashSet<Prescription>();
            this.PrescriptionsListForPatient = new HashSet<Prescription>();
        }
    
        public long Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public bool IsDoctor { get; set; }
        public bool Enabled { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool SidebarMode { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string CNP { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsPatient { get; set; }
        public Nullable<System.DateTime> LastAuthDate { get; set; }
    
        public virtual ICollection<UsersProfile> UsersProfiles { get; set; }
        public virtual ICollection<Appointment> AppointmentsListForDoctor { get; set; }
        public virtual ICollection<Appointment> AppointmentsListForPatient { get; set; }
        public virtual ICollection<Prescription> PrescriptionsListForDoctor { get; set; }
        public virtual ICollection<Prescription> PrescriptionsListForPatient { get; set; }
    }
}
