//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesira.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersState
    {
        public UsersState()
        {
            this.UsersProfiles = new HashSet<UsersProfile>();
        }
    
        public int Id { get; set; }
        public string State { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<UsersProfile> UsersProfiles { get; set; }
    }
}
